name: base_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4
  go_router: ^13.0.0 
  shared_preferences: ^2.2.2
  floor: ^1.4.2
  flutter_localizations:
    sdk: flutter
  intl: any  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/gen/
