name: base_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  floor: ^1.4.2
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_local_notifications: ^16.2.0

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
